# Junktown
{100}{}{They never have what I want.}
{101}{}{I think the selection is getting worse.}
{102}{}{These prices are getting out of hand.}
{103}{}{I can never find what I want.}
{104}{}{I like the Crimson Caravan's selection better.}
# BOS
{105}{}{They never have what I want.}
{106}{}{I think the selection is getting worse.}
{107}{}{These prices are getting out of hand.}
{108}{}{Sorry, I'm not supposed to talk to outsiders.}
{109}{}{You should see Cabbot or Darrell if you have questions.}
# Necropolis
{110}{}{Getta going.}
{111}{}{I don wanna talk to you.}
{112}{}{I don like normies.}
{113}{}{Arrrr!}
{114}{}{Grrrrr!}
# LABone
{115}{}{They never have what I want.}
{116}{}{I think the selection is getting worse.}
{117}{}{These prices are getting out of hand.}
{118}{}{I can never find what I want.}
{119}{}{I like the Crimson Caravan's selection better.}
