#!/usr/bin/env bash
# Toggle compile-time Rebirth diagnostics logging for release readiness.
# This controls F1R_DISABLE_RME_LOGGING through .f1r-build.env.
#
# Usage:
#   ./scripts/patch/rebirth-toggle-logging.sh --status
#   ./scripts/patch/rebirth-toggle-logging.sh --disable
#   ./scripts/patch/rebirth-toggle-logging.sh --enable
#   ./scripts/patch/rebirth-toggle-logging.sh --disable --reconfigure-macos
#   ./scripts/patch/rebirth-toggle-logging.sh --enable --reconfigure-ios
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_FILE="${STATE_FILE:-$ROOT_DIR/.f1r-build.env}"

MODE="status"
RECONFIGURE_MACOS=0
RECONFIGURE_IOS=0

usage() {
    cat <<EOF
Fallout 1 Rebirth logging toggle

Usage:
  $(basename "$0") --status
  $(basename "$0") --disable [--reconfigure-macos] [--reconfigure-ios]
  $(basename "$0") --enable  [--reconfigure-macos] [--reconfigure-ios]
  $(basename "$0") --state-file <path> ...

Modes:
  --disable    Compile out Rebirth/patch diagnostics (F1R_DISABLE_RME_LOGGING=1)
  --enable     Compile in Rebirth/patch diagnostics (F1R_DISABLE_RME_LOGGING=0)
  --status     Show the current mode (default)

Notes:
  - Build scripts source \$ROOT/.f1r-build.env when present.
  - Reconfiguration triggers a clean configure pass for requested platform builds.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --status)
            MODE="status"
            shift
            ;;
        --disable)
            MODE="disable"
            shift
            ;;
        --enable)
            MODE="enable"
            shift
            ;;
        --reconfigure-macos)
            RECONFIGURE_MACOS=1
            shift
            ;;
        --reconfigure-ios)
            RECONFIGURE_IOS=1
            shift
            ;;
        --state-file)
            STATE_FILE="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

current_value() {
    if [[ -f "$STATE_FILE" ]]; then
        awk -F= '/^export F1R_DISABLE_RME_LOGGING=/{print $2; exit}' "$STATE_FILE"
    else
        echo ""
    fi
}

print_status() {
    local v
    v="$(current_value)"
    if [[ -z "$v" ]]; then
        echo "Logging mode: ENABLED (default; no state file found at $STATE_FILE)"
        return
    fi

    case "$v" in
        1|ON|on|true|TRUE|yes|YES)
            echo "Logging mode: DISABLED (compile-time, from $STATE_FILE)"
            ;;
        *)
            echo "Logging mode: ENABLED (compile-time, from $STATE_FILE)"
            ;;
    esac
}

write_state() {
    local v="$1"
    mkdir -p "$(dirname "$STATE_FILE")"
    cat >"$STATE_FILE" <<EOF
# Generated by scripts/patch/rebirth-toggle-logging.sh
# Build scripts source this file automatically.
export F1R_DISABLE_RME_LOGGING=$v
EOF
}

run_reconfigure() {
    local value="$1"
    if [[ "$RECONFIGURE_MACOS" -eq 1 ]]; then
        echo "Reconfiguring macOS build with F1R_DISABLE_RME_LOGGING=$value"
        (
            cd "$ROOT_DIR"
            CLEAN=1 F1R_DISABLE_RME_LOGGING="$value" ./scripts/build/build-macos.sh
        )
    fi

    if [[ "$RECONFIGURE_IOS" -eq 1 ]]; then
        echo "Reconfiguring iOS build with F1R_DISABLE_RME_LOGGING=$value"
        (
            cd "$ROOT_DIR"
            CLEAN=1 F1R_DISABLE_RME_LOGGING="$value" ./scripts/build/build-ios.sh
        )
    fi
}

case "$MODE" in
    status)
        print_status
        ;;
    disable)
        write_state "1"
        echo "Set logging mode to DISABLED in $STATE_FILE"
        run_reconfigure "1"
        ;;
    enable)
        write_state "0"
        echo "Set logging mode to ENABLED in $STATE_FILE"
        run_reconfigure "0"
        ;;
esac
