#!/usr/bin/env bash
# Toggle compile-time Rebirth diagnostics logging for release readiness.
# This controls F1R_DISABLE_RME_LOGGING through .f1r-build.env.
#
# Usage:
#   ./scripts/test/test-rebirth-toggle-logging.sh --status
#   ./scripts/test/test-rebirth-toggle-logging.sh --disable
#   ./scripts/test/test-rebirth-toggle-logging.sh --enable
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STATE_FILE="${STATE_FILE:-$ROOT_DIR/.f1r-build.env}"

MODE="status"

usage() {
    cat <<EOF
Fallout 1 Rebirth logging toggle

Usage:
  $(basename "$0") --status
  $(basename "$0") --disable
  $(basename "$0") --enable
  $(basename "$0") --state-file <path> ...

Modes:
  --disable    Compile out Rebirth/patch diagnostics (F1R_DISABLE_RME_LOGGING=1)
  --enable     Compile in Rebirth/patch diagnostics (F1R_DISABLE_RME_LOGGING=0)
  --status     Show the current mode (default)

Notes:
  - Build scripts source \$ROOT/.f1r-build.env when present.
  - This script never builds or reconfigures artifacts.
  - After changing this setting, run an explicit build command:
      ./scripts/build/build-macos.sh -prod
      ./scripts/build/build-ios.sh -prod --device
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --status)
            MODE="status"
            shift
            ;;
        --disable)
            MODE="disable"
            shift
            ;;
        --enable)
            MODE="enable"
            shift
            ;;
        --state-file)
            STATE_FILE="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

current_value() {
    if [[ -f "$STATE_FILE" ]]; then
        awk -F= '/^export F1R_DISABLE_RME_LOGGING=/{print $2; exit}' "$STATE_FILE"
    else
        echo ""
    fi
}

print_status() {
    local v
    v="$(current_value)"
    if [[ -z "$v" ]]; then
        echo "Logging mode: ENABLED (default; no state file found at $STATE_FILE)"
        return
    fi

    case "$v" in
        1|ON|on|true|TRUE|yes|YES)
            echo "Logging mode: DISABLED (compile-time, from $STATE_FILE)"
            ;;
        *)
            echo "Logging mode: ENABLED (compile-time, from $STATE_FILE)"
            ;;
    esac
}

write_state() {
    local v="$1"
    mkdir -p "$(dirname "$STATE_FILE")"
    cat >"$STATE_FILE" <<EOF
# Generated by scripts/test/test-rebirth-toggle-logging.sh
# Build scripts source this file automatically.
export F1R_DISABLE_RME_LOGGING=$v
EOF
}

print_rebuild_instructions() {
    local value="$1"
    echo "Next step: rebuild artifacts with F1R_DISABLE_RME_LOGGING=$value"
    echo "  ./scripts/build/build-macos.sh -prod"
    echo "  ./scripts/build/build-ios.sh -prod --device"
}

case "$MODE" in
    status)
        print_status
        ;;
    disable)
        write_state "1"
        echo "Set logging mode to DISABLED in $STATE_FILE"
        print_rebuild_instructions "1"
        ;;
    enable)
        write_state "0"
        echo "Set logging mode to ENABLED in $STATE_FILE"
        print_rebuild_instructions "0"
        ;;
esac
